### ISSUE TITLE
How add second network card to virtualbox image?

### ISSUE THREAD

**Issue by patsevanton** [jdeathe/packer-centos-7#47]
Hello!
How add second network card to virtualbox image?
Can you add new CentOS-7-Minimal-virtualbox.json with 2 network card?
Thanks!

**Comment by jdeathe** [comment]
Hi @patsevanton,

Thank you for your interest in this project. Adding a second network card is not something that is required at the image level. You can add network cards via VirtualBox either via the UI, via the CLI or via Vagrant depending on your use-case.

**Comment by patsevanton** [comment]
Thanks!
